
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador_Sintactico;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int eof = 55;
  public static final int igualigual = 21;
  public static final int mayque = 22;
  public static final int corchc = 52;
  public static final int rvoid = 45;
  public static final int dif = 26;
  public static final int corcha = 51;
  public static final int porigual = 19;
  public static final int mod = 14;
  public static final int menosigual = 18;
  public static final int relse = 37;
  public static final int rreturn = 42;
  public static final int txt = 5;
  public static final int rread = 53;
  public static final int coma = 47;
  public static final int rdefault = 35;
  public static final int Operador = 2;
  public static final int divigual = 20;
  public static final int igual = 9;
  public static final int men = 25;
  public static final int rlong = 41;
  public static final int rswitch = 44;
  public static final int rbreak = 30;
  public static final int masigual = 17;
  public static final int menosmenos = 8;
  public static final int puntoycoma = 48;
  public static final int masmas = 7;
  public static final int menque = 24;
  public static final int may = 23;
  public static final int rif = 39;
  public static final int menos = 11;
  public static final int rwhile = 46;
  public static final int EOF = 0;
  public static final int parc = 16;
  public static final int mas = 10;
  public static final int Palabra_reservada = 3;
  public static final int rint = 40;
  public static final int para = 15;
  public static final int error = 1;
  public static final int rchar = 32;
  public static final int rfor = 38;
  public static final int or = 27;
  public static final int por = 12;
  public static final int punto = 49;
  public static final int rcase = 31;
  public static final int dospuntos = 50;
  public static final int rcontinue = 34;
  public static final int rshort = 43;
  public static final int Identificador = 6;
  public static final int and = 28;
  public static final int not = 29;
  public static final int rconst = 33;
  public static final int div = 13;
  public static final int num = 4;
  public static final int rwrite = 54;
  public static final int rdo = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Operador",
  "Palabra_reservada",
  "num",
  "txt",
  "Identificador",
  "masmas",
  "menosmenos",
  "igual",
  "mas",
  "menos",
  "por",
  "div",
  "mod",
  "para",
  "parc",
  "masigual",
  "menosigual",
  "porigual",
  "divigual",
  "igualigual",
  "mayque",
  "may",
  "menque",
  "men",
  "dif",
  "or",
  "and",
  "not",
  "rbreak",
  "rcase",
  "rchar",
  "rconst",
  "rcontinue",
  "rdefault",
  "rdo",
  "relse",
  "rfor",
  "rif",
  "rint",
  "rlong",
  "rreturn",
  "rshort",
  "rswitch",
  "rvoid",
  "rwhile",
  "coma",
  "puntoycoma",
  "punto",
  "dospuntos",
  "corcha",
  "corchc",
  "rread",
  "rwrite",
  "eof"
  };
}

